// user
export const USER_NAME_UPDATE = 'USER_NAME_UPDATE';

export const USER_AUTH_LOADING = 'USER_AUTH_LOADING';
export const USER_SUCCESSFUL_SIGN_IN = 'USER_SUCCESSFUL_SIGN_IN';
export const USER_SUCCESSFUL_SIGN_OUT = 'USER_SUCCESSFUL_SIGN_OUT';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';